# Form implementation generated from reading ui file './templates/dlg_GestionProp.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_dlg_TipoProp(object):
    def setupUi(self, dlg_TipoProp):
        dlg_TipoProp.setObjectName("dlg_TipoProp")
        dlg_TipoProp.resize(400, 300)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("./templates\\../img/logo.ico"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        dlg_TipoProp.setWindowIcon(icon)
        self.widget = QtWidgets.QWidget(parent=dlg_TipoProp)
        self.widget.setGeometry(QtCore.QRect(0, 30, 391, 241))
        self.widget.setObjectName("widget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame = QtWidgets.QFrame(parent=self.widget)
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.widget1 = QtWidgets.QWidget(parent=self.frame)
        self.widget1.setGeometry(QtCore.QRect(20, 10, 351, 91))
        self.widget1.setObjectName("widget1")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget1)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lblGestTipoProp = QtWidgets.QLabel(parent=self.widget1)
        self.lblGestTipoProp.setMinimumSize(QtCore.QSize(250, 20))
        self.lblGestTipoProp.setMaximumSize(QtCore.QSize(350, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lblGestTipoProp.setFont(font)
        self.lblGestTipoProp.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lblGestTipoProp.setObjectName("lblGestTipoProp")
        self.verticalLayout.addWidget(self.lblGestTipoProp)
        self.txtGestTipoProp = QtWidgets.QLineEdit(parent=self.widget1)
        self.txtGestTipoProp.setMinimumSize(QtCore.QSize(150, 20))
        self.txtGestTipoProp.setMaximumSize(QtCore.QSize(150, 20))
        self.txtGestTipoProp.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.txtGestTipoProp.setObjectName("txtGestTipoProp")
        self.verticalLayout.addWidget(self.txtGestTipoProp, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.verticalLayout_2.addWidget(self.frame)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.btnAltaTipoProp = QtWidgets.QPushButton(parent=self.widget)
        self.btnAltaTipoProp.setMinimumSize(QtCore.QSize(80, 25))
        self.btnAltaTipoProp.setMaximumSize(QtCore.QSize(80, 25))
        self.btnAltaTipoProp.setObjectName("btnAltaTipoProp")
        self.horizontalLayout.addWidget(self.btnAltaTipoProp)
        self.btnDelTipoProp = QtWidgets.QPushButton(parent=self.widget)
        self.btnDelTipoProp.setMinimumSize(QtCore.QSize(80, 25))
        self.btnDelTipoProp.setMaximumSize(QtCore.QSize(80, 25))
        self.btnDelTipoProp.setObjectName("btnDelTipoProp")
        self.horizontalLayout.addWidget(self.btnDelTipoProp)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout_2.addLayout(self.horizontalLayout)

        self.retranslateUi(dlg_TipoProp)
        QtCore.QMetaObject.connectSlotsByName(dlg_TipoProp)

    def retranslateUi(self, dlg_TipoProp):
        _translate = QtCore.QCoreApplication.translate
        dlg_TipoProp.setWindowTitle(_translate("dlg_TipoProp", "Gestion Tipo Prop"))
        self.lblGestTipoProp.setText(_translate("dlg_TipoProp", "INTRODUZCA EL TIPO DE PROPIEDAD A CREAR O ELIMINAR"))
        self.btnAltaTipoProp.setText(_translate("dlg_TipoProp", "Alta"))
        self.btnDelTipoProp.setText(_translate("dlg_TipoProp", "Eliminar"))
