# Form implementation generated from reading ui file './templates/dlg_listadoPropiedades.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_dlg_ListadoProp(object):
    def setupUi(self, dlg_ListadoProp):
        dlg_ListadoProp.setObjectName("dlg_ListadoProp")
        dlg_ListadoProp.resize(400, 300)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("./templates\\../img/logo.ico"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        dlg_ListadoProp.setWindowIcon(icon)
        dlg_ListadoProp.setModal(True)
        self.verticalLayoutWidget = QtWidgets.QWidget(parent=dlg_ListadoProp)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(100, 90, 160, 80))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(parent=self.verticalLayoutWidget)
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.chkElegirProp = QtWidgets.QComboBox(parent=self.verticalLayoutWidget)
        self.chkElegirProp.setEditable(True)
        self.chkElegirProp.setObjectName("chkElegirProp")
        self.verticalLayout.addWidget(self.chkElegirProp)
        self.btnGenerarInforme = QtWidgets.QPushButton(parent=self.verticalLayoutWidget)
        self.btnGenerarInforme.setObjectName("btnGenerarInforme")
        self.verticalLayout.addWidget(self.btnGenerarInforme)

        self.retranslateUi(dlg_ListadoProp)
        QtCore.QMetaObject.connectSlotsByName(dlg_ListadoProp)

    def retranslateUi(self, dlg_ListadoProp):
        _translate = QtCore.QCoreApplication.translate
        dlg_ListadoProp.setWindowTitle(_translate("dlg_ListadoProp", "Gestion Tipo Prop"))
        self.label.setText(_translate("dlg_ListadoProp", "Elija una propiedad"))
        self.btnGenerarInforme.setText(_translate("dlg_ListadoProp", "Generar"))
