# Form implementation generated from reading ui file './templates/dlgAbout.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_dlgAbout(object):
    def setupUi(self, dlgAbout):
        dlgAbout.setObjectName("dlgAbout")
        dlgAbout.setWindowModality(QtCore.Qt.WindowModality.NonModal)
        dlgAbout.resize(595, 326)
        dlgAbout.setModal(True)
        self.btnSalir = QtWidgets.QPushButton(parent=dlgAbout)
        self.btnSalir.setGeometry(QtCore.QRect(500, 290, 75, 23))
        self.btnSalir.setObjectName("btnSalir")
        self.label = QtWidgets.QLabel(parent=dlgAbout)
        self.label.setGeometry(QtCore.QRect(30, 60, 171, 181))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("./templates\\../img/casa.ico"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=dlgAbout)
        self.label_2.setGeometry(QtCore.QRect(220, 10, 231, 71))
        font = QtGui.QFont()
        font.setPointSize(30)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(parent=dlgAbout)
        self.label_3.setGeometry(QtCore.QRect(220, 70, 331, 201))
        self.label_3.setTextFormat(QtCore.Qt.TextFormat.AutoText)
        self.label_3.setScaledContents(False)
        self.label_3.setWordWrap(True)
        self.label_3.setObjectName("label_3")

        self.retranslateUi(dlgAbout)
        QtCore.QMetaObject.connectSlotsByName(dlgAbout)

    def retranslateUi(self, dlgAbout):
        _translate = QtCore.QCoreApplication.translate
        dlgAbout.setWindowTitle(_translate("dlgAbout", "Dialog"))
        self.btnSalir.setText(_translate("dlgAbout", "Aceptar"))
        self.label_2.setText(_translate("dlgAbout", "INMO TEIS"))
        self.label_3.setText(_translate("dlgAbout", "<html><head/><body><p><br/>Versión 1.0.0</p><p>Copyright © [1998-2024] Inmoteis&amp;Co. Todos los derechos reservados.</p><p>Este sitio web y su contenido están protegidos por derechos de autor y otras leyes de propiedad intelectual aplicables.</p><p>El uso de este producto está sujeto a los Términos y Condiciones de Uso.</p><p>Licenciado a: Amán Lama Vilariño</p><p>El uso no autorizado de este sitio web, su contenido o materiales asociados puede dar lugar a acciones legales.</p></body></html>"))
